# fly.toml app configuration file generated for themarketplace on 2023-12-25T20:00:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "themarketplace"
primary_region = "ewr"

[build]
  image = "isomer04/themarketplace:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dwcitlwgb"
  CloudinarySettings__ApiKey="959217497192423"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
